namespace Qudi.Generator;

/// <summary>
/// Contains reusable code template contents.
/// </summary>
internal static class CodeTemplateContents
{
    public const string CommonGeneratedHeader = $"""
        // <auto-generated>
        // This code was generated by Qudi.Generator (Ver: {ThisAssembly.AssemblyInformationalVersion})
        // </auto-generated>
        #nullable enable
        """;

    public const string EditorBrowsableAttribute =
        "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";

    public const string EmbeddedAttributeUsage =
        "[global::Microsoft.CodeAnalysis.EmbeddedAttribute]";

    public const string EmbeddedAttributeSource = $$"""
        namespace Microsoft.CodeAnalysis
        {
            internal sealed partial class EmbeddedAttribute : global::System.Attribute { }
        }
        """;
}
